### ISSUE TITLE
match is only accurate when paid monthly

### ISSUE THREAD

**Issue by achernet** [circld/match_maximizer#1]
https://github.com/circld/match_maximizer/blob/7b1ba6ceb952f61a1732df0f6dfe4a87b23d7253/match_maximizer/core.py#L76

**Comment by paulgrow-octane** [comment]
Great catch-- test was passing because, of course, I was setting the number of pay periods to 12. 

Fixed in latest commit 1876e32 👍

**Comment by circld** [comment]
Great catch-- test was passing because, of course, I was setting the number of pay periods to 12. 

Fixed in latest commit 1876e32 👍
